### ISSUE TITLE
Where can I find the file named ''test.json''?

### ISSUE THREAD

**Issue by ZifeiMo96** [ofsoundof/GRL-Image-Restoration#10]
It is a great job and I am very interested in it. I have downloaded your code and pre-trained model. But I meet some trouble when running your code.
I follow the 'ReadME.Md' file to set the environment and use this command to run your code.
`torchx run -- -j 1x2 -- \
    -m training=False gpus=2 experiment=dm/grl model=grl/grl_small \
    load_state_dict=True pretrained_checkpoint="${MODEL_ZOO}/GRL/dm_grl_small.ckpt"`
But when the code runs to line 96 of the "/GRL-Image-Restoration-main/data/datasets/restoration_dn.py" file, it gets an error that says the "test.json" file cannot be found. And the specific error information is as follows.
`FileNotFoundError: [Errno 2] No such file or directory: '/root/projects/data/LightningIR/image_info/McMaster/test.json'`

I've gone through all of your code, but I can't find a similar ". json " file, so I'm wondering where I can find the "test. json" file.

**Comment by ofsoundof** [comment]
Thanks a lot for the question. Please download image_info.zip from the [release](https://github.com/ofsoundof/GRL-Image-Restoration/releases/tag/v1.0.0).

**Comment by ZifeiMo96** [comment]
Thank you very much for your reply. It helps a lot
