### ISSUE TITLE
The code seems to be wrong？

### ISSUE THREAD

**Issue by bnm6900030** [ofsoundof/GRL-Image-Restoration#12]
The norm should precede the computation of attention.
such as：

![微信图片_20230406204615](https://user-images.githubusercontent.com/34081561/230385288-323f73fe-f09f-4fd2-854f-944958156a1b.png)

**Comment by ofsoundof** [comment]
No, this is not a bug. This design is inspired by Swin Transformer V2.

**Comment by bnm6900030** [comment]
Thank you for response, I found that post-norm seems to perform better when I was reproducing your code.
Maybe by accident.

**Comment by ofsoundof** [comment]
According to my experiments, post-norm does performs better.
