### ISSUE TITLE
hydra.errors.InstantiationException: Error locating target 'data.IRDataModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.

### ISSUE THREAD

**Issue by zxiol** [ofsoundof/GRL-Image-Restoration#13]
Hello, do you know how to solve this problem? I put the data_ module:
_ target_: ' Change 'data. IRDataModule' to_ target_: ' data.data_ module.ir_ data_ Module. IRDataModule 'still reported an error. Best wishes
<img width="1014" alt="Snipaste_2023-04-14_20-19-00" src="https://user-images.githubusercontent.com/125778426/232041511-b2e76251-5120-42da-a9d2-b5be42940fd8.png">

**Comment by nharodig** [comment]
> Hello, do you know how to solve this problem? I put the data_ module: _ target_: ' Change 'data. IRDataModule' to_ target_: ' data.data_ module.ir_ data_ Module. IRDataModule 'still reported an error. Best wishes <img alt="Snipaste_2023-04-14_20-19-00" width="1014" src="https://user-images.githubusercontent.com/125778426/232041511-b2e76251-5120-42da-a9d2-b5be42940fd8.png">

Hello, I'm having a similar problem, were you able to solve it?

**Comment by zxiol** [comment]
My issue is caused by environmental issues. You need to create a new environment, conda create - n LightningIR Python=3.8, and download the required packages. Secondly, it is necessary to_ target_ The path for 'data. IRDataModule 'changed to_ target_: '  data.data_module.ir_data_Module.IRDataModule '

**Comment by Wenzzzhhh** [comment]
> My issue is caused by environmental issues. You need to create a new environment, conda create - n LightningIR Python=3.8, and download the required packages. Secondly, it is necessary to_ target_ The path for 'data. IRDataModule 'changed to_ target_: ' data.data_module.ir_data_Module.IRDataModule '

This issue is still exist after I to_ target_ The path for 'data. IRDataModule 'changed to_ target_: ' data.data_module.ir_data_Module.IRDataModule '.Do you have any other advices for this issue?
