### ISSUE TITLE
 two questions about the experimental results and evaluation indicators

### ISSUE THREAD

**Issue by zxiol** [ofsoundof/GRL-Image-Restoration#15]
Congratulations, I have two questions about the experimental results and evaluation indicators.
1. What do the results HQ and LQ generated by the denoising task (dn) represent? Are high-quality images and low-quality images? Does LQ represent the noisy image I input?
2. Which two images are used to calculate the evaluation indicators PSNR and SSIM? Because I seem to have only inputted noisy images without corresponding reference images. What does the 'y' in 'psnr_y' represent?
Thank you very much for your reply
<img width="192" alt="Snipaste_2023-04-17_20-12-33" src="https://user-images.githubusercontent.com/125778426/232480510-3d63e8c5-2386-4f77-a897-30603a0e41f9.png">
<img width="217" alt="Snipaste_2023-04-17_20-13-14" src="https://user-images.githubusercontent.com/125778426/232480717-c80db456-3314-4fb1-9803-f3dcbff2da85.png">

**Comment by ofsoundof** [comment]
Thanks a lot for the question! The following are my answers.
1. HQ: the restored high-quality images. For image denoising, this is the denoised image.
2. LQ: this is the low-quality image. For image denoising, it is the noisy input.
3. The ground-truth image and the restored images (HQ) are used to calculate PSNR and SSIM. Actually, for Gaussian image denoising, the input of the dataloader is the ground-truth images and the noisy images are generated on the fly.
4. Y means the Y channel. So `psnr_y` is the PSNR calculated on the Y channel. And `psnr` without `y` suffix is the PSNR calculated on the RGB channels.
