### ISSUE TITLE
Error loading model due to missing keys in state dictionary calculated by 'get_relative_coords_table_all'

### ISSUE THREAD

**Issue by rotem154154** [ofsoundof/GRL-Image-Restoration#4]
Thank you very much for making this model available as open source! 
I am having trouble loading the model because I am getting an error message indicating that some keys are missing from the state dictionary. 
I have noticed that all of the missing keys are associated with the function 'get_relative_coords_table_all'. Could you please let me know if there is anything I am missing or doing incorrectly?

"table_w", "table_sh", "table_sv", "index_w", "index_sh_a2w", "index_sh_w2a", "index_sv_a2w", "index_sv_w2a", "mask_w", "mask_sh_a2w", "mask_sh_w2a", "mask_sv_a2w", "mask_sv_w2a".

**Comment by DZY-irene** [comment]
I met the same problem.  How did you solve it?

**Comment by dolphin0104** [comment]
Please let me know. I met the same problem as well.
