### ISSUE TITLE
Is there an error in the self-attention expression?Eq(1)

### ISSUE THREAD

**Issue by ZhiyingDu** [ofsoundof/GRL-Image-Restoration#8]
When calculating the time complexity of Self-attention, is the expression of Q = WQ · X reversed? At the same time, the dimension of X should also be reversed?

**Comment by ZhiyingDu** [comment]
The ’error‘ exits in Eq.(1).

**Comment by ofsoundof** [comment]
It's a typo. We already corrected in the camera ready.
